import os
from dotenv import load_dotenv
from scripts.notion_utils import append_heading, append_bullet, write_paragraph_to_notion

# Load .env vars
load_dotenv()

# Choose which page to target
page_id = os.getenv("NOTION_PAGE_ID_MASTER")
print("📘 Writing to page:", page_id)

# Step 1 – Add section title
append_heading(page_id, "📌 GPT Research Summary", level=2)

# Step 2 – Add bullets
bullets = ["Concepts we've learned", "Useful prompts", "Agent outputs"]
for bullet in bullets:
    append_bullet(page_id, bullet)

# Step 3 – Add a follow-up paragraph
write_paragraph_to_notion(page_id,
                          "✅ This section was generated by the Notion Agent.")
